#!/bin/bash
# See http://michal.karzynski.pl/blog/2013/06/09/django-nginx-gunicorn-virtualenv-supervisor/

export PATH="/var/www:/var/www/kvmate:${PATH}"

NAME="kvmate"
DJANGODIR=/var/www/kvmate/kvmate
SOCKFILE=/var/www/run/kvmate.sock
PIDFILE=/var/www/run/kvmate.pid
USER=www-data
GROUP=www-data
NUM_WORKERS=1
DJANGO_SETTINGS_MODULE=kvmate.settings.production
DJANGO_WSGI_MODULE=kvmate.wsgi

echo "Starting $NAME"

# Activate the virtual environment
cd $DJANGODIR
source /usr/local/bin/virtualenvwrapper.sh
export WORKON_HOME=/var/www/.envs
workon kvmate_production

# Create the run directory if it doesn't exist
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR

# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
exec gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $NUM_WORKERS \
  --user=$USER --group=$GROUP \
  --log-level=debug \
  --bind=unix:$SOCKFILE \
  --pid $PIDFILE
